#!/usr/bin/env bash
#
# ClaimMate local setup helper.
#
#   ./setup.sh
#
# Checks prerequisites, installs dependencies, helps you create .env.local,
# and bundles the migrations into one paste-ready file for the Supabase SQL
# editor. Safe to re-run. Skips interactive prompts when stdin isn't a TTY.

set -euo pipefail

cd "$(dirname "$0")"

bold() { printf '\033[1m%s\033[0m\n' "$1"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$1"; }
info() { printf '  \033[36m→\033[0m %s\n' "$1"; }

interactive=false
[ -t 0 ] && interactive=true

# Read a value with a prompt/default; blank stays blank. No-op when non-TTY.
ask() { # ask <var> <prompt> <default>
  local __var="$1" __prompt="$2" __default="${3:-}" __reply=""
  if ! $interactive; then printf -v "$__var" '%s' "$__default"; return; fi
  if [ -n "$__default" ]; then
    read -r -p "  $__prompt [$__default]: " __reply || true
    [ -z "$__reply" ] && __reply="$__default"
  else
    read -r -p "  $__prompt (enter to skip): " __reply || true
  fi
  printf -v "$__var" '%s' "$__reply"
}

bold "1. Checking prerequisites"
if ! command -v node >/dev/null 2>&1; then
  warn "Node.js not found. Install Node 20+ from https://nodejs.org and re-run."
  exit 1
fi
node_major="$(node -p 'process.versions.node.split(".")[0]')"
if [ "$node_major" -lt 20 ]; then
  warn "Node $(node -v) found, but ClaimMate needs Node 20+. Please upgrade."
  exit 1
fi
ok "Node $(node -v)"
command -v npm >/dev/null 2>&1 || { warn "npm not found"; exit 1; }
ok "npm $(npm -v)"

bold "2. Installing dependencies"
npm install
ok "Dependencies installed"

bold "3. Configuring .env.local"
if [ -f .env.local ]; then
  ok ".env.local already exists — leaving it untouched"
else
  ask SUPA_URL "Supabase Project URL" ""
  ask SUPA_ANON "Supabase anon public key" ""
  ask SITE_URL "Site URL" "http://localhost:3000"
  ask ANTHROPIC "Anthropic API key (optional, enables AI tools)" ""

  cat > .env.local <<ENV
NEXT_PUBLIC_SUPABASE_URL=${SUPA_URL:-}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPA_ANON:-}
NEXT_PUBLIC_SITE_URL=${SITE_URL:-http://localhost:3000}

# Server-side only — never expose to the browser
ANTHROPIC_API_KEY=${ANTHROPIC:-}

# Optional: dense-vector policy clause retrieval (falls back to full-text search)
VOYAGE_API_KEY=

# Optional: charge for evidence packs (leave unset for free exports)
STRIPE_SECRET_KEY=
STRIPE_PRICE_ID=
STRIPE_WEBHOOK_SECRET=
SUPABASE_SERVICE_ROLE_KEY=
ENV
  ok "Wrote .env.local"
  if [ -z "${SUPA_URL:-}" ] || [ -z "${SUPA_ANON:-}" ]; then
    warn "Supabase URL/key are blank — the app runs but sign-in won't work until you fill them in."
  fi
fi

bold "4. Bundling migrations"
combined="supabase/combined_migrations.sql"
{
  echo "-- Generated by setup.sh — all migrations in order."
  echo "-- Paste this whole file into the Supabase SQL editor and run it once."
  echo
  for f in supabase/migrations/*.sql; do
    echo "-- ============================================================"
    echo "-- $(basename "$f")"
    echo "-- ============================================================"
    cat "$f"
    echo
  done
} > "$combined"
count="$(find supabase/migrations -name '*.sql' | wc -l | tr -d ' ')"
ok "Bundled $count migrations → $combined"

# Offer to push via the Supabase CLI if it's installed and the project is linked.
if command -v supabase >/dev/null 2>&1; then
  info "Supabase CLI detected. If this project is linked (supabase link), you can run: supabase db push"
fi

bold "Next steps"
cat <<'STEPS'
  1. Create a Supabase project at https://supabase.com (if you haven't).
  2. In the Supabase SQL editor, paste and run:  supabase/combined_migrations.sql
  3. In Authentication → URL Configuration, set the Site URL to your NEXT_PUBLIC_SITE_URL.
  4. Make sure .env.local has your Supabase URL + anon key, then start the app:

       npm run dev

     Open http://localhost:3000 and sign up.

  Optional:
  • Populate a demo claim: put your email at the top of supabase/seed.sql and run it.
  • Unlock the policy admin: update profiles set is_admin = true where email = 'you@…';
STEPS
