import {
  Document,
  Image,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";
import { formatDate, formatDateTime } from "@/lib/format";
import {
  CLAIM_STATUS_META,
  claimTypeLabel,
  type Claim,
} from "@/types/claims";
import { EVIDENCE_CATEGORY_LABELS, type EvidenceItem } from "@/types/evidence";
import {
  TIMELINE_EVENT_LABELS,
  type CallLog,
  type TimelineEvent,
} from "@/types/timeline";

export interface ExportSections {
  evidence: boolean;
  timeline: boolean;
  calls: boolean;
  aiSummary: boolean;
  policyAnswer: boolean;
}

export interface ExportData {
  claim: Claim;
  evidence: Array<EvidenceItem & { imageDataUri: string | null }>;
  timeline: TimelineEvent[];
  calls: CallLog[];
  aiSummary: string | null;
  policyAnswer: string | null;
  policySummary: string | null;
  generatedAtIso: string;
  sections: ExportSections;
}

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#16202a",
  },
  coverTitle: { fontSize: 24, fontFamily: "Helvetica-Bold", marginBottom: 8 },
  coverSub: { fontSize: 12, color: "#566472", marginBottom: 24 },
  h2: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    marginTop: 16,
    marginBottom: 6,
    color: "#235452",
  },
  h3: { fontSize: 11, fontFamily: "Helvetica-Bold", marginTop: 8, marginBottom: 2 },
  body: { lineHeight: 1.5, marginBottom: 4 },
  muted: { color: "#566472" },
  disclaimerBox: {
    marginTop: 24,
    padding: 10,
    backgroundColor: "#f0f3f4",
    borderRadius: 4,
  },
  row: { flexDirection: "row", marginBottom: 2 },
  rowLabel: { width: 120, color: "#566472" },
  rowValue: { flex: 1 },
  evidenceImage: {
    maxHeight: 240,
    objectFit: "contain",
    marginTop: 4,
    marginBottom: 8,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#566472",
    textAlign: "center",
  },
  aiLabel: {
    fontSize: 9,
    color: "#1f5fa8",
    marginBottom: 4,
    fontFamily: "Helvetica-Bold",
  },
});

function Field({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.row}>
      <Text style={styles.rowLabel}>{label}</Text>
      <Text style={styles.rowValue}>{value}</Text>
    </View>
  );
}

function Footer({ generated }: { generated: string }) {
  return (
    <Text style={styles.footer} fixed>
      Generated by ClaimMate on {generated}. Organised claim record — not
      legal, financial or insurance advice.
    </Text>
  );
}

function ClaimPack({ data }: { data: ExportData }) {
  const { claim, sections } = data;
  const generated = formatDateTime(data.generatedAtIso);

  return (
    <Document
      title={`${claim.title} — ClaimMate evidence pack`}
      author="ClaimMate"
    >
      <Page size="A4" style={styles.page}>
        <Text style={styles.coverTitle}>{claim.title}</Text>
        <Text style={styles.coverSub}>
          ClaimMate evidence pack · generated {generated}
        </Text>

        <Text style={styles.h2}>Claim snapshot</Text>
        <Field label="Claim type" value={claimTypeLabel(claim)} />
        <Field label="Incident date" value={formatDate(claim.incident_date)} />
        <Field
          label="Location"
          value={claim.incident_location ?? "Not provided"}
        />
        <Field label="Status" value={CLAIM_STATUS_META[claim.status].label} />
        <Field label="Insurer" value={claim.insurer_name ?? "Not provided"} />
        <Field
          label="Claim number"
          value={claim.claim_number ?? "Not provided"}
        />
        <Field
          label="Policy number"
          value={claim.policy_number ?? "Not provided"}
        />
        {data.policySummary && (
          <Field label="Policy" value={data.policySummary} />
        )}

        <Text style={styles.h2}>What happened</Text>
        <Text style={styles.body}>{claim.description}</Text>
        {claim.urgent_needs && (
          <>
            <Text style={styles.h3}>Urgent needs</Text>
            <Text style={styles.body}>{claim.urgent_needs}</Text>
          </>
        )}

        {sections.aiSummary && data.aiSummary && (
          <>
            <Text style={styles.h2}>Claim summary</Text>
            <Text style={styles.aiLabel}>
              AI-GENERATED DRAFT — reviewed by the claim owner before sending
            </Text>
            <Text style={styles.body}>{data.aiSummary}</Text>
          </>
        )}

        <View style={styles.disclaimerBox}>
          <Text style={styles.muted}>
            This pack was assembled by the policyholder using ClaimMate from
            their own records, photos and notes. It organises information; it
            does not provide legal, financial or insurance advice, and it does
            not assert coverage or entitlement.
          </Text>
        </View>
        <Footer generated={generated} />
      </Page>

      {sections.timeline && data.timeline.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.h2}>Timeline</Text>
          <Text style={{ ...styles.body, ...styles.muted }}>
            Incident occurred {formatDate(claim.incident_date)} (from claim
            details).
          </Text>
          {data.timeline.map((event) => (
            <View key={event.id} wrap={false}>
              <Text style={styles.h3}>
                {formatDate(event.event_date)} —{" "}
                {TIMELINE_EVENT_LABELS[event.event_type]}: {event.title}
              </Text>
              {event.description && (
                <Text style={styles.body}>{event.description}</Text>
              )}
            </View>
          ))}
          <Footer generated={generated} />
        </Page>
      )}

      {sections.calls && data.calls.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.h2}>Call log</Text>
          {data.calls.map((call) => (
            <View key={call.id} wrap={false}>
              <Text style={styles.h3}>
                {formatDateTime(call.call_date)} — {call.organisation}
                {call.person_spoken_to ? ` (${call.person_spoken_to})` : ""}
              </Text>
              <Text style={styles.body}>{call.summary}</Text>
              {call.promises_made && (
                <Text style={styles.body}>Promised: {call.promises_made}</Text>
              )}
              {call.next_steps && (
                <Text style={styles.body}>Next steps: {call.next_steps}</Text>
              )}
            </View>
          ))}
          <Footer generated={generated} />
        </Page>
      )}

      {sections.evidence && data.evidence.length > 0 && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.h2}>
            Evidence ({data.evidence.length} item
            {data.evidence.length === 1 ? "" : "s"})
          </Text>
          {data.evidence.map((item) => (
            <View key={item.id} wrap={false}>
              <Text style={styles.h3}>{item.file_name}</Text>
              <Text style={{ ...styles.body, ...styles.muted }}>
                {EVIDENCE_CATEGORY_LABELS[item.category]}
                {item.captured_at
                  ? ` · captured ${formatDate(item.captured_at)}`
                  : ""}{" "}
                · added {formatDate(item.created_at)}
              </Text>
              {item.user_notes && (
                <Text style={styles.body}>{item.user_notes}</Text>
              )}
              {item.imageDataUri && (
                // eslint-disable-next-line jsx-a11y/alt-text
                <Image src={item.imageDataUri} style={styles.evidenceImage} />
              )}
            </View>
          ))}
          <Footer generated={generated} />
        </Page>
      )}

      {sections.policyAnswer && data.policyAnswer && (
        <Page size="A4" style={styles.page}>
          <Text style={styles.h2}>Policy wording explanation</Text>
          <Text style={styles.aiLabel}>
            AI-GENERATED, SOURCE-BACKED EXPLANATION — based only on retrieved
            policy wording; confirm with the insurer or a qualified adviser
          </Text>
          <Text style={styles.body}>{data.policyAnswer}</Text>
          <Footer generated={generated} />
        </Page>
      )}
    </Document>
  );
}

export async function renderClaimPack(data: ExportData): Promise<Buffer> {
  return renderToBuffer(<ClaimPack data={data} />);
}
